version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaSegura!@#
    ports:
      - "1433:1433"
    networks:
      - sql_network
    restart: unless-stopped

networks:
  sql_network:
    driver: bridge
